# Generated by Django 5.2.7 on 2025-11-12 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 12, 9, 51, 21, 898216, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 12, 9, 51, 29, 24260, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
