# Generated by Django 5.2.7 on 2025-11-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_numbers',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
