# Generated by Django 5.2.7 on 2025-11-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_ticket_status_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
