# Generated by Django 5.2.7 on 2025-11-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_ticket_seat_number_ticket_seat_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_numbers',
            field=models.CharField(),
        ),
    ]
