# Generated by Django 5.2.7 on 2025-11-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_ticket_seat_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='seat_numbers',
            new_name='seat_number',
        ),
    ]
