# Generated by Django 5.2.7 on 2025-11-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='airlines',
            field=models.ManyToManyField(to='airlines.airline'),
        ),
    ]
